# 1. 점포 데이터 전처리

. 기준년, 분기, 상권코드, 서비스업종기준으로 존재하는 점포 데이터  
. 결측치 없음  
. 데이터 unique key 값 : '기준_년_코드','상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '서비스_업종_코드'

1. 2020년부터 2021년까지의 데이터를 가지고 있으므로 최종 데이터인 2021년 데이터 선택  
2. 계절성을 없애고 기준년, 상권구분, 상권코드, 서비스 업종 기반으로 분석하기 위해 데이터 전처리(각 점포 상권코드, 서비스업종 코드 별 평균값)

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./data/서울시 우리마을가게 상권분석서비스(상권-점포).csv', encoding='cp949')

In [4]:
df.head()

,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2021,4,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,8,8,0,0,0,0,0
1,2021,4,U,관광특구,1001496,강남 마이스 관광특구,CS300042,주유소,1,1,0,0,0,0,0
2,2021,4,U,관광특구,1001496,강남 마이스 관광특구,CS300041,예술품,10,10,0,0,0,0,0
3,2021,4,U,관광특구,1001496,강남 마이스 관광특구,CS300038,자동차부품,10,10,0,0,0,0,0
4,2021,4,U,관광특구,1001496,강남 마이스 관광특구,CS300036,조명용품,14,14,0,0,0,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598403 entries, 0 to 598402
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   기준_년_코드      598403 non-null  int64
 1   기준_분기_코드     598403 non-null  int64
 2   상권_구분_코드     598403 non-null  object
 3   상권_구분_코드_명   598403 non-null  object
 4   상권_코드        598403 non-null  int64
 5   상권_코드_명      598403 non-null  object
 6   서비스_업종_코드    598403 non-null  object
 7   서비스_업종_코드_명  598403 non-null  object
 8   점포_수         598403 non-null  int64
 9   유사_업종_점포_수   598403 non-null  int64
 10  개업_율         598403 non-null  int64
 11  개업_점포_수      598403 non-null  int64
 12  폐업_률         598403 non-null  int64
 13  폐업_점포_수      598403 non-null  int64
 14  프랜차이즈_점포_수   598403 non-null  int64
dtypes: int64(10), object(5)
memory usage: 68.5+ MB

### 1. 2020년부터 2021년까지의 데이터를 가지고 있으므로 최종 데이터인 2021년 데이터 선택

In [6]:
df_1 = df.loc[df['기준_년_코드']==2021]

### 2. 계절성을 없애고 기준년, 상권구분, 상권코드, 서비스 업종 기반으로 분석하기 위해 데이터 전처리
. 각 점포 상권코드, 서비스업종 코드 별 평균값

In [7]:
df.columns

Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')

In [8]:
# 3.3 계절성을 없애고 기준년, 상권구분, 상권코드, 서비스 업종 기반으로 분석하기 위해 데이터 전처리 
jg_groupby_col = ['점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수']

df_2 = df_1.groupby(['기준_년_코드','상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',  '서비스_업종_코드', '서비스_업종_코드_명']).mean()[jg_groupby_col].reset_index()

In [ ]:
######### mean이 맞는건지..?

In [9]:
df_2

,기준_년_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,서비스_업종_코드,서비스_업종_코드_명,점포_수,유사_업종_점포_수,개업_율,개업_점포_수,폐업_률,폐업_점포_수,프랜차이즈_점포_수
0,2021,A,골목상권,2110001,이북5도청사,CS100001,한식음식점,10.0,11.0,2.25,0.25,2.25,0.25,1.0
1,2021,A,골목상권,2110001,이북5도청사,CS100008,분식전문점,3.0,3.0,0.00,0.00,0.00,0.00,0.0
2,2021,A,골목상권,2110001,이북5도청사,CS100009,호프-간이주점,0.5,1.5,0.00,0.00,25.00,0.25,1.0
3,2021,A,골목상권,2110001,이북5도청사,CS100010,커피-음료,2.0,2.0,12.50,0.25,12.50,0.25,0.0
4,2021,A,골목상권,2110001,이북5도청사,CS200001,일반교습학원,3.0,3.0,0.00,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76221,2021,U,관광특구,1001496,강남 마이스 관광특구,CS300036,조명용품,14.0,14.0,0.00,0.00,0.00,0.00,0.0
76222,2021,U,관광특구,1001496,강남 마이스 관광특구,CS300038,자동차부품,10.0,10.0,0.00,0.00,0.00,0.00,0.0
76223,2021,U,관광특구,1001496,강남 마이스 관광특구,CS300041,예술품,9.5,9.5,2.50,0.25,0.00,0.00,0.0
76224,2021,U,관광특구,1001496,강남 마이스 관광특구,CS300042,주유소,1.0,1.0,0.00,0.00,0.00,0.00,0.0
76225,2021,U,관광특구,1001496,강남 마이스 관광특구,CS300043,전자상거래업,8.0,8.0,0.00,0.00,0.00,0.00,0.0

In [12]:
df_2.to_csv('./data/3.점포_전처리완료.csv' , encoding='cp949')